### ISSUE TITLE
Mainline tracking

### ISSUE THREAD

**Issue by LambdaSix** [LambdaSix/Wild-Living#74]
Updates required for new Nested Container PR:

- [ ] Convert CONTAINER to GENERIC for water-storage vessels
- [ ] Rework storage items to new pocket_data format
- [ ] Take opportunity to introduce aspects of #73 and #66 as possible.
- [ ] Refactor for bullet_resist changes to materials
- [ ] Play-testing above changes

**Comment by LambdaSix** [comment]
As experimental builds are now stable(ish), this can be packaged up into a 0.4E (experimental) build for release when I have time.
